version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DASHBOARD_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DASHBOARD_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DASHBOARD_POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    image: acem:1.0
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
